language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.7
  - 2.2.3
env:
  global:
    - PUPESOFT_TEST_DATABASE="pupesoft_test"
    - PUPESOFT_TEST_USERNAME="travis"
    - PUPESOFT_TEST_PASSWORD=""
    - PUPESOFT_TEST_HOSTNAME="127.0.0.1"
    - RAILS_ENV=test
notifications:
  email: false
  flowdock:
    secure: "VpZzmGHK6X/CHj09N0nnNLQhUjqi43S/H0FqXmbODNqyZtEFoMr2xHfdo5CgAhoM1oc9Y65jCm4zL7qPMzSsMdHiYJOgdVJDgCERkn11pDMNIrNZ6SUhQIyTiLAroEk8kDMj9eyv3GGgwntqs4dpEfs+b6n6Ul5f2QjriWcOK98="
addons:
  apt:
    packages:
    - qrencode
  code_climate:
    repo_token:
      secure: "Pcqd4D943MPPCfnikGleJikdmBDsoesydI7Jb+X9RxwBUjizbLXkBJOE1+KvULsBdOXQo/5Ld22MbT9/eE3ZSoprJ5q8cmg38zAO5fQQXd75kMb3ol30sJeYA/gsYIuhLE+YthJdLkl8H2Z2zVzuSoCmKXPburJB6dV2rsU2nLU="
before_install:
install:
before_script:
  - mysql -e 'create database pupesoft_test default character set latin1;'
script:
  - bundle install
  - bundle exec rake
  - bundle exec i18n-tasks health fi
after_success:
after_failure:
after_script:
