language: ruby
rvm:
  - 2.1.1
env:
  global:
    - PUPESOFT_TEST_DATABASE="pupesoft_test"
    - PUPESOFT_TEST_USERNAME="travis"
    - PUPESOFT_TEST_PASSWORD=""
    - PUPESOFT_TEST_HOSTNAME="127.0.0.1"
    - SECRET_KEY_BASE=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
notifications:
  email: false
  flowdock:
    secure: "Twrq8ErfHJvn0t8gGRkBSgoNnycJE+KVduVKUITIPazSSNMRzgjRpbJYReZdyiSjclCBo1rHol/3K9Eq59NmQxovpd2JqNpNO9PIbZ6D4SoS6TEYymMjBYeSjqJpn7xh97S1nD3tRpRVIux4HVPCoGHd0zPqnnWtDFszYGGMpRU="
addons:
  code_climate:
    repo_token:
      secure: "Pcqd4D943MPPCfnikGleJikdmBDsoesydI7Jb+X9RxwBUjizbLXkBJOE1+KvULsBdOXQo/5Ld22MbT9/eE3ZSoprJ5q8cmg38zAO5fQQXd75kMb3ol30sJeYA/gsYIuhLE+YthJdLkl8H2Z2zVzuSoCmKXPburJB6dV2rsU2nLU="
before_install:
install:
  - gem install bundler -v 1.6.2
before_script:
  - mysql -e 'create database pupesoft_test;'
  - mysql -u root -e 'SET GLOBAL storage_engine=myisam;'
script:
  - bundle install
  - bundle exec rake
after_success:
after_failure:
after_script:
